# -*- coding: utf-8 -*-
"""
/***************************************************************************
 PaddockPower
                                 A QGIS plugin
 Tools for Paddock Power Project
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2020-01-16
        git sha              : $Format:%H$
        copyright            : (C) 2020 by Northern Territory Government
        email                : dale.jenner@nt.gov.au
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""
import os
import sys
import inspect
from PyQt5.QtWidgets import QAction
from PyQt5.QtGui import QIcon

from qgis.core import QgsProcessingAlgorithm, QgsApplication
import processing
from .paddock_power_providers import PaddockPowerProviders

cmd_folder = os.path.split(inspect.getfile(inspect.currentframe()))[0]


class PaddockPower:
    
    def __init__(self, iface):
        self.iface = iface
        
    def initProcessing(self):
        self.provider = PaddockPowerProviders()
        QgsApplication.processingRegistry().addProvider(self.provider)

    def initGui(self):
        self.initProcessing()
        self.first_start = True
        
              
    def unload(self):
        QgsApplication.processingRegistry().removeProvider(self.provider)
    