# -*- coding: utf-8 -*-
"""
/***************************************************************************
 PaddockPowerDialog
                                 A QGIS plugin
 Tools for Paddock Power Project
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2020-01-16
        git sha              : $Format:%H$
        copyright            : (C) 2020 by Northern Territory Government
        email                : dale.jenner@nt.gov.au
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import os

from qgis.PyQt import uic
from qgis.PyQt import QtWidgets

# This loads your .ui file so that PyQt can populate your plugin with the elements from Qt Designer
Ui_SplitPaddockDialogBase = uic.loadUiType(os.path.join(os.path.dirname(__file__), 'split_paddock_dialog_base.ui'))[0]
Ui_WPAnalysisDialogBase = uic.loadUiType(os.path.join(os.path.dirname(__file__), 'WPAnalysis_dialog_base.ui'))[0]
Ui_FenceAnalysisDialogBase = uic.loadUiType(os.path.join(os.path.dirname(__file__), 'FenceAnalysis_dialog_base.ui'))[0]
Ui_PipelineAnalysisDialogBase = uic.loadUiType(os.path.join(os.path.dirname(__file__), 'PipelineAnalysis_dialog_base.ui'))[0]


class SplitPaddockDialog(QtWidgets.QDialog, Ui_SplitPaddockDialogBase):
    def __init__(self, parent=None):
        """Constructor."""
        super(SplitPaddockDialog, self).__init__(parent)
        # Set up the user interface from Designer through FORM_CLASS.
        # After self.setupUi() you can access any designer object by doing
        # self.<objectname>, and you can use autoconnect slots - see
        # http://qt-project.org/doc/qt-4.8/designer-using-a-ui-file.html
        # #widgets-and-dialogs-with-auto-connect
        self.setupUi(self)
        
        
class WPAnalysisDialog(QtWidgets.QDialog, Ui_WPAnalysisDialogBase):
    def __init__(self, parent=None):
        """Constructor."""
        super(WPAnalysisDialog, self).__init__(parent)
        # Set up the user interface from Designer through FORM_CLASS.
        # After self.setupUi() you can access any designer object by doing
        # self.<objectname>, and you can use autoconnect slots - see
        # http://qt-project.org/doc/qt-4.8/designer-using-a-ui-file.html
        # #widgets-and-dialogs-with-auto-connect
        self.setupUi(self)

class FenceAnalysisDialog(QtWidgets.QDialog, Ui_FenceAnalysisDialogBase):
    def __init__(self, parent=None):
        """Constructor."""
        super(FenceAnalysisDialog, self).__init__(parent)
        # Set up the user interface from Designer through FORM_CLASS.
        # After self.setupUi() you can access any designer object by doing
        # self.<objectname>, and you can use autoconnect slots - see
        # http://qt-project.org/doc/qt-4.8/designer-using-a-ui-file.html
        # #widgets-and-dialogs-with-auto-connect
        self.setupUi(self)
        
class PipelineAnalysisDialog(QtWidgets.QDialog, Ui_PipelineAnalysisDialogBase):
    def __init__(self, parent=None):
        """Constructor."""
        super(PipelineAnalysisDialog, self).__init__(parent)
        # Set up the user interface from Designer through FORM_CLASS.
        # After self.setupUi() you can access any designer object by doing
        # self.<objectname>, and you can use autoconnect slots - see
        # http://qt-project.org/doc/qt-4.8/designer-using-a-ui-file.html
        # #widgets-and-dialogs-with-auto-connect
        self.setupUi(self)