"""Initialise SpatiaLite and clean up unwanted artifacts

Revision ID: 7abf0c8f8043
Revises: 
Create Date: 2023-03-07 21:50:58.611470

"""
# -*- coding: utf-8 -*-
from alembic import op
import sqlalchemy as sa
import geoalchemy2
import mlapp_schema.data
import mlapp_schema.data.models 



# revision identifiers, used by Alembic.
revision = '7abf0c8f8043'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Unused
    op.drop_table('sql_statements_log')
    
    # Deprecated by SpatiaLite
    op.drop_table('KNN')

    # ### end Alembic commands ###


def downgrade() -> None:
    pass