"""Initialise SpatiaLite and clean up unwanted artifacts

Revision ID: 7abf0c8f8043
Revises: 
Create Date: 2023-03-07 21:50:58.611470

"""
# -*- coding: utf-8 -*-
from alembic import op
import sqlalchemy as sa
import geoalchemy2
import mlapp_schema.data
import mlapp_schema.data.models 



# revision identifiers, used by Alembic.
revision = '7abf0c8f8043'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('SpatialIndex')
    op.drop_table('data_licenses')
    op.drop_table('sql_statements_log')
    op.drop_table('KNN')
    op.drop_table('ElementaryGeometries')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ElementaryGeometries',
    sa.Column('db_prefix', sa.TEXT(), nullable=True),
    sa.Column('f_table_name', sa.TEXT(), nullable=True),
    sa.Column('f_geometry_column', sa.TEXT(), nullable=True),
    sa.Column('origin_rowid', sa.INTEGER(), nullable=True),
    sa.Column('item_no', sa.INTEGER(), nullable=True),
    sa.Column('geometry', sa.BLOB(), nullable=True)
    )
    op.create_table('KNN',
    sa.Column('f_table_name', sa.TEXT(), nullable=True),
    sa.Column('f_geometry_column', sa.TEXT(), nullable=True),
    sa.Column('ref_geometry', sa.BLOB(), nullable=True),
    sa.Column('max_items', sa.INTEGER(), nullable=True),
    sa.Column('pos', sa.INTEGER(), nullable=True),
    sa.Column('fid', sa.INTEGER(), nullable=True),
    sa.Column('distance', sa.DOUBLE(), nullable=True)
    )
    op.create_table('sql_statements_log',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('time_start', sa.TIMESTAMP(), server_default=sa.text("'0000-01-01T00:00:00.000Z'"), nullable=False),
    sa.Column('time_end', sa.TIMESTAMP(), server_default=sa.text("'0000-01-01T00:00:00.000Z'"), nullable=False),
    sa.Column('user_agent', sa.TEXT(), nullable=False),
    sa.Column('sql_statement', sa.TEXT(), nullable=False),
    sa.Column('success', sa.INTEGER(), server_default=sa.text('0'), nullable=False),
    sa.Column('error_cause', sa.TEXT(), server_default=sa.text("'ABORTED'"), nullable=False),
    sa.CheckConstraint('success IN (0,1))', name='sqllog_success'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('data_licenses',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('name', sa.TEXT(), nullable=False),
    sa.Column('url', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('SpatialIndex',
    sa.Column('f_table_name', sa.TEXT(), nullable=True),
    sa.Column('f_geometry_column', sa.TEXT(), nullable=True),
    sa.Column('search_frame', sa.BLOB(), nullable=True)
    )
    # ### end Alembic commands ###
